// Hello"Coder"...
// Hello\Coder\...
// Hello
// Coder...
// Hello   Coder...
// HellCoder...
public class escape_sequence {
    public static void main(String[] args) {
        System.out.println("Hello\"Coder\"...");
        System.out.println("Hello\\Coder\\...");
        System.out.println("Hello\nCoder...");
        System.out.println("Hello\tCoder...");
        System.out.println("Hello\bCoder...");
    }
    
}
